"""V5.6 identity quality reasons (Phase 25).

Exact suspension reasons for FAILED_QUALITY; never generic "low
confidence". Naming follows the project's UPPER_SNAKE domain-error
convention (app/domain/errors.py).
"""
from __future__ import annotations

POLARITY_AMBIGUOUS = "POLARITY_AMBIGUOUS"
ANATOMICAL_SIDE_UNRESOLVED = "ANATOMICAL_SIDE_UNRESOLVED"
MULTIVIEW_IDENTITY_CONFLICT = "MULTIVIEW_IDENTITY_CONFLICT"
ANATOMICAL_INCONSISTENCY = "ANATOMICAL_INCONSISTENCY"
TEMPORAL_IDENTITY_CONFLICT = "TEMPORAL_IDENTITY_CONFLICT"
INSUFFICIENT_IDENTITY_EVIDENCE = "INSUFFICIENT_IDENTITY_EVIDENCE"

ALL_REASONS = (POLARITY_AMBIGUOUS, ANATOMICAL_SIDE_UNRESOLVED,
               MULTIVIEW_IDENTITY_CONFLICT, ANATOMICAL_INCONSISTENCY,
               TEMPORAL_IDENTITY_CONFLICT, INSUFFICIENT_IDENTITY_EVIDENCE)

__all__ = ["POLARITY_AMBIGUOUS", "ANATOMICAL_SIDE_UNRESOLVED",
           "MULTIVIEW_IDENTITY_CONFLICT", "ANATOMICAL_INCONSISTENCY",
           "TEMPORAL_IDENTITY_CONFLICT", "INSUFFICIENT_IDENTITY_EVIDENCE",
           "ALL_REASONS"]
